Avoid unneccessarily running the completed orders query
woocommerce/woocommerce-google-analytics-integration pull request #197
Opened 2021-08-30 16:53 UTC by ArtskydJ

### All Submissions:

* [x] Does your code follow the [WordPress](https://make.wordpress.org/core/handbook/best-practices/coding-standards/) coding standards?

### Changes proposed in this Pull Request:

The `woocommerce_google_analytics_pro_notice_shown` now gets set to `true` when there are over 100 completed orders, so that the query counting the orders will not be executed again.

Closes #163.

### Other information:

* [x] Have you checked to ensure there aren't other open [Pull Requests](../../pulls) for the same update/change?

### Changelog entry

> Avoid unneccessarily running the completed orders query

2021-09-10 14:08 UTC, layoutd requested changes
Thanks for this PR, @Artskydj. 👍🏻  Just one small code style suggestion.

We've also had some discussion about the action itself: could you change it from `init` to `admin_init` (so the notice logic isn't run on every single public page load) before we merge the PR?
https://github.com/woocommerce/woocommerce-google-analytics-integration/blob/5e54e59ae19cf8be949ff6dbcca142db01bfb6f3/woocommerce-google-analytics-integration.php#L43

Once those two changes are made, we can merge the PR, and and include the changes in next week's release!

2021-09-10 14:08 UTC, layoutd commented on woocommerce-google-analytics-integration.php
> +			$too_many_orders_to_show_the_notice = $completed_orders > 100;
```suggestion
			$too_few_orders_to_show_the_notice  = $completed_orders < 10;
			$too_many_orders_to_show_the_notice = $completed_orders > 100;
```
Align variable assignments.

2021-09-13 20:03 UTC, ArtskydJ commented on woocommerce-google-analytics-integration.php
> +			$too_many_orders_to_show_the_notice = $completed_orders > 100;
Fixed in c9449d8

2021-09-13 20:08 UTC, ArtskydJ commented
Thanks!  I've updated `init` ⏩ `admin_init`, and fixed the unaligned whitespace.

2021-09-14 12:52 UTC, layoutd approved these changes
Looks good, thanks for the changes @ArtskydJ! 

I'll merge the PR, and the changes should be included in release 1.5.2 early next week.

2021-09-14 13:03 UTC, merged