Add/onboarding task wc
woocommerce/woocommerce-google-analytics-integration pull request #235
Opened 2022-10-31 11:16 UTC by jorgemd24

### Changes proposed in this Pull Request:

Closes  peeuvX-6w-p2

This PR adds a new task in WooCommerce's "Things to do next" section.

![image](https://user-images.githubusercontent.com/2488994/198992982-b7c1be60-542b-4bbf-aac5-faea4438629e.png)

The task contains:
- The "Google Analytics Integration"
- A link to set up the configuration.
- The estimated time to complete the task: 5min.

The configuration is completed once is set the "Google Analytics Tracking ID".

![image](https://user-images.githubusercontent.com/2488994/198993170-2b8d1d96-7459-4db5-b27e-e8692f28a920.png)

In order to give a more consistent experience through the different extensions the following banner has been removed:

![image](https://user-images.githubusercontent.com/2488994/198994159-c0f7f0f3-cd4c-4e66-80f3-606bbee2cb90.png)

### Checks:

* [X] Does your code follow the [WordPress](https://make.wordpress.org/core/handbook/best-practices/coding-standards/) coding standards?
* [ ] Have you written new tests for your changes, as applicable?
* [X] Have you successfully run tests with your changes locally?
* [X] Have you checked to ensure there aren't other open [Pull Requests](../../pulls) for the same update/change?

### Detailed test instructions:

1. Go to Woocomme Dashboard - wp-admin/admin.php?page=wc-admin
2. A new task should be displayed: Set up Google Analytics
3. Google Analytics should be completed if a "Google Analytics Tracking ID" has been set previously otherwise will be uncompleted.
4. Click on the task. It should go to the settings page.
5. Add or remove "Google Analytics Tracking ID" and the status of the task should change to complete/uncompleted.
6. No banners should be displayed if the Google Analytics Tracking ID is not set.

### Changelog entry
> Add - New Google Analytics task in WC

2022-11-01 10:51 UTC, martynmjones commented
Looks like this is working great with WooCommerce version 6.4.0 onward 👍. There are a couple of backward compatibility issues that I mentioned in a comment.

2022-11-02 08:50 UTC, jorgemd24 commented
Thanks, @martynmjones for having a look at this, 

>There are a couple of backward compatibility issues that I mentioned in a comment.

Can you point me to the comment? I can not see it 😄 

Thanks!

2022-11-02 08:52 UTC, martynmjones requested changes

2022-11-02 08:52 UTC, martynmjones commented on includes/class-wc-google-analytics-task.php
> +use Automattic\WooCommerce\Admin\Features\OnboardingTasks\Task;
On a site with <= WC version 5.8 installed this triggers a critical error because `OnboardingTasks\Task` wasn't available at that point but the extension is currently checking for a [minimum version of WC 3.2](https://github.com/woocommerce/woocommerce-google-analytics-integration/blob/617ec963d512ce454d1e665fe76cf89530471b74/woocommerce-google-analytics-integration.php#L57).

It also looks like there is an issue with abstract method declarations from WC version 6.1.0 which also triggers a fatal error.

2022-11-02 08:54 UTC, martynmjones commented
> Thanks, @martynmjones for having a look at this,
> 
> > There are a couple of backward compatibility issues that I mentioned in a comment.
> 
> Can you point me to the comment? I can not see it 😄
> 
> Thanks!

Sorry Jorge, didn't submit the [review](https://github.com/woocommerce/woocommerce-google-analytics-integration/pull/235/files/617ec963d512ce454d1e665fe76cf89530471b74#r1010302740) 🥱 ☕

2022-11-02 15:36 UTC, jorgemd24 commented
@martynmjones thanks for catching this.

>On a site with <= WC version 5.8 installed this triggers a critical error because OnboardingTasks\Task wasn't available at that point but the extension is currently checking for a [minimum version of WC 3.2](https://github.com/woocommerce/woocommerce-google-analytics-integration/blob/617ec963d512ce454d1e665fe76cf89530471b74/woocommerce-google-analytics-integration.php#L57).

I did some investigation and I can see that the issue is because WC 5.8.0 uses   [WC admin. V2.7.2](https://github.com/woocommerce/woocommerce/blob/d9620e89de7d473ac2f8962091dbe6d4990d76cf/composer.json#L24) and the class was introduced in V2.8.0

>It also looks like there is an issue with abstract method declarations from WC version 6.1.0 which also triggers a fatal error.

WC 6.1.0 uses V3.0.3 and it has an abstract method [get_parent_id](https://github.com/woocommerce/woocommerce-admin/blob/0b1abab35c62717f3121428fe7f378998ef4899c/src/Features/OnboardingTasks/Task.php#L75) than in the later versions has been implemented in the class, so the method is not abstract anymore.

I think it is a good opportunity to update the minimum WC version required to run the plugin, as I think we need to be aligned with the [L2 WC](https://developer.woocommerce.com/2020/05/08/wordpress-core-support-policy/) and [the team's policy](https://automatap2.wordpress.com/how-we-work/environment-developer-distribution/) meaning that we support the current version and the last two versions of WC.

I have updated the code with the WC minimum version and the error message if the user does not comply the minimum requirements.

2022-11-03 13:39 UTC, martynmjones approved these changes

2022-11-03 13:42 UTC, martynmjones commented
> I think it is a good opportunity to update the minimum WC version required to run the plugin, as I think we need to be aligned with the [L2 WC](https://developer.woocommerce.com/2020/05/08/wordpress-core-support-policy/) and [the team's policy](PeeuvX-1t-p2) meaning that we support the current version and the last two versions of WC.
> 
> I have updated the code with the WC minimum version and the error message :
> 
> ![image](https://user-images.githubusercontent.com/2488994/199596707-4924a573-5048-4023-80c8-59688e4b3b57.png)

Thanks for the detailed response! No longer seeing any errors triggered by the extension regardless of WC version so LGTM 👍

2022-11-03 16:40 UTC, merged